### ISSUE TITLE
Omnipose installation issue

### ISSUE THREAD

**Issue by ved-sharma** [kevinjohncutler/omnipose#10]
Hello,

I am trying to install Omnipose on my Windows 10 machine using Anaconda prompt:

```
>conda create --name omnipose python=3.8.5
>conda activate omnipose
>pip install omnipose
>python -m omnipose
```
Everything seems to install properly. When I run the last line, I get the following error:
```
(omnipose) D:\>python -m omnipose
Traceback (most recent call last):
  File "C:\Users\xxxx\.conda\envs\omnipose\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\xxxx\.conda\envs\omnipose\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\xxxx\.conda\envs\omnipose\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\xxxx\.conda\envs\omnipose\lib\site-packages\omnipose\__init__.py", line 1, in <module>
    from . import core
  File "C:\Users\xxxx\.conda\envs\omnipose\lib\site-packages\omnipose\core.py", line 6, in <module>
    from sklearn.utils.extmath import cartesian
ModuleNotFoundError: No module named 'sklearn'
```

Instead, if I try to install omnipose in a new env using the Git dev version
```
>pip install git+https://github.com/kevinjohncutler/omnipose.git
```

Again, it installs properly but when I run "python -m omnipose", I get the following error:
```
(omnipose2) D:\>python -m omnipose
GUI ERROR: No module named 'PyQt6'
GUI FAILED: GUI dependencies may not be installed, to install, run
     pip install cellpose[gui]
```
I also tried to install cellpose[gui], but the error persists.

Can you please help?

Thanks,
Ved

**Comment by kevinjohncutler** [comment]
@ved-sharma, sorry you may have encountered this issue around the time that I was updating to PyQt6 (I had temporarily removed the PyQt dependency for debugging). It appears to be working fine across all the machines I have tested, but please reopen this issue if you are still having problems.
