### ISSUE TITLE
Contour missing

### ISSUE THREAD

**Issue by WuJunxu** [kevinjohncutler/omnipose#101]
Thanks for your great work!
While I tried to get the unique contour by calling the function **omnipose.core.get_contour()**, I got contour missing.

``` python
contour_map, contour_list, unique_L = omnipose.core.get_contour(msk, affinity_graph, coords, cardinal_only=1)
```

The white region in mask is the background, and the missing contour is in the transition of bg and fg.
The missing contour present bellow (red rectangle region):

| mask | boundary | contour |
|----|----|----|
| ![image](https://github.com/kevinjohncutler/omnipose/assets/49099380/4157a229-b400-432f-92cb-fa0e7989941f) | ![image](https://github.com/kevinjohncutler/omnipose/assets/49099380/4161d03f-96cc-4f71-b280-7f1bdd15bacf) | ![image](https://github.com/kevinjohncutler/omnipose/assets/49099380/9c66399f-a553-4843-92a4-61ce9b1dcd63) |

**Comment by kevinjohncutler** [comment]
@WuJunxu that is interesting! It also looks like it is not properly returning the contours between masks. They should be pairs of closed loops (indexed from 0 to N-1 where N is the number of pixels on the contour) but only one side of each interface is getting a contour. Also the edges of the image are not recognized as part of the contour. I'll have to look up my code for using this function, as it was more for internal development.  Stay tuned.

**Comment by kevinjohncutler** [comment]
@WuJunxu could you share this example mask when you get the chance?

**Comment by kevinjohncutler** [comment]
Here is a link to a new docs page I have added to demo the use of the contour function:
https://omnipose.readthedocs.io/contours.html

**Comment by kevinjohncutler** [comment]
@WuJunxu closing now, please reopen if the example code does not resolve your issue. Thanks!
