### ISSUE TITLE
Models load to omnipose

### ISSUE THREAD

**Issue by BornKrefeld** [kevinjohncutler/omnipose#104]
How I can load models omnipose? The process seems to me unclear. Is cellpose or cellpose-omni the destination

**Comment by kevinjohncutler** [comment]
@BornKrefeld Sorry for the delay. Please refer to the [example mono_channel_bact notebook](https://omnipose.readthedocs.io/examples/mono_channel_bact.html) in docs/examples to see how to load a named model. For custom models, use the `pretrained_model` argument in `models.CellposeModel`. Cellpose_omni replaces Cellpose, so for example `from cellpose_omni import models` is the right syntax. Cellpose should not be installed in the same environment. Please reopen if you have any other questions or comments.
