### ISSUE TITLE
Issue with numpy 2.0.1 - ValueError: numpy.dtype size changed

### ISSUE THREAD

**Issue by Tom-TBT** [kevinjohncutler/omnipose#105]
Hello,
I just installed omnipose from this post to avoid the scipy import error https://github.com/kevinjohncutler/omnipose/issues/78#issuecomment-2181421101

Running the example notebook "mono_channel_bact", I stumble upon the error:
`ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

I found this fix that worked for me: https://stackoverflow.com/a/78641304
`pip install --upgrade numpy==1.26.4`

**Comment by kevinjohncutler** [comment]
Thanks for posting this. This has to do with numba and numpy and cython. One thing is that pip is not automatically updating numba to 0.60.0. The other is that cythonized packages like fastremap need to be updated too, so I put 1.26.4 as the max version for numpy earlier this year in the omnipose dependencies.
