### ISSUE TITLE
Issue with old pytorch version

### ISSUE THREAD

**Issue by lguerard** [kevinjohncutler/omnipose#17]
Hi,

I have been having issue with omnipose in the last couple of days and found out that the `mps` support in your latest version of Cellpose is giving issues with old version of `pytorch` (1.8.2) as it doesn't have `backends`. Would it be possible to bypass this for older `pytorch` version ?

Thanks !

**Comment by kevinjohncutler** [comment]
Great point. I think I can do a version check of pytorch before calling that function to avoid that issue.

**Comment by kevinjohncutler** [comment]
Ok, latest version (including pip versions of `omnipose` and `cellpose-omni`) have fixed this issue. I just use a try/except branch to catch it for any version lacking `backends`.
