### ISSUE TITLE
command to segment cellpose images based on omnipose

### ISSUE THREAD

**Issue by JunMa11** [kevinjohncutler/omnipose#19]
Thanks for the awesome work.

is this the correct command to segment the cellpose dataset based on omnipose?

```bash
python -m omnipose  --dir path to/cellpose-data --pretrained_model cyto2_omni --chan 2 --chan2 1 --save_tif --savedir path to/cyto2-omni-cellpose-data --dir_abov --no_npy --save_outlines --diameter 30
```

**Comment by kevinjohncutler** [comment]
@JunMa11 That looks right. Good just to compare against the [docs](https://omnipose.readthedocs.io/examples/multi_channel_cyto.html). In particular, I have some comments about the channel arguments. The original cellpose cyto dataset has red nuclei and green cytosol. I flip those in the jupyter notebook, but for the raw image in CLI, you would want: 

```
python -m omnipose  --dir <path_to_folder> --pretrained_model cyto2_omni --chan 1 --chan2 2
```
![000_img_outlines](https://user-images.githubusercontent.com/39454982/197095645-ee11afeb-76f6-4695-a474-482146ca0b18.png)
