### ISSUE TITLE
Issues training on CLI

### ISSUE THREAD

**Issue by carolche** [kevinjohncutler/omnipose#23]
Hello,
I am trying to train my model on Omnipose CLI, but I keep getting two different errors:
1) raise RuntimeError('affine matrix has wrong number of rows')
2) AttributeError: 'CPnet' object has no attribute 'module'. Did you mean: 'modules'?
 I tried using my own images as well as data from the Stardist training set. Any help would be greatly appreciated.

![Screen Shot 2022-10-25 at 14 15 15](https://user-images.githubusercontent.com/77370541/197688533-317ad3c2-4def-4582-b81c-44fbafce41fb.png)
![Screen Shot 2022-10-25 at 14 15 41](https://user-images.githubusercontent.com/77370541/197688536-f2886ef9-29eb-467b-9ea2-38cf93e0f8b7.png)

Thanks so much for your work and help.

**Comment by JojoDevel** [comment]
I am getting exactly the same error

**Comment by JojoDevel** [comment]
The problem seems to be in this if/else statement. When I disable the `if` the training runs through.
https://github.com/kevinjohncutler/cellpose/blob/6b6a2888745c2a6afe9fdc02c35165fba31f15a8/cellpose/core.py#L1051

**Comment by kevinjohncutler** [comment]
@JojoDevel @carolche Could you let me know which version of pytorch you have installed with `pip list`? I am running 1.12.1 with no training issues, but the torch API and cuda support changes so frequently that upgrading to 1.13.0 or downgrading to 1.8.1 caused two compeltely different issues to the one you raise. Let me know your cuda version as well, if applicable (could be a training on CPU issue, which I'll take a look at as well - might be likely considering that note on the if statement).

**Comment by kevinjohncutler** [comment]
Ok, @JojoDevel that if/else was entirely removed in cellpose a long time ago (presumably this an mxnet/torch compatibility thing). Download v0.7.2 cellpose-omni for the fixed version!

**Comment by carolche** [comment]
@kevinjohncutler I downloaded the 0.7.2 cellpose-omni version and it worked!  Thank you so much! take care

**Comment by JojoDevel** [comment]
@kevinjohncutler I just looked into the cellpose submodule in the repo. Is that not in sync with the cellpose version we should use?
