### ISSUE TITLE
098-117 shape mismatch in testing set

### ISSUE THREAD

**Issue by JunMa11** [kevinjohncutler/omnipose#3]
Dear Omnipose,

Thanks for sharing the awesome work.
I find some cases have shape-mismatch issues in the testing set.

image name   mask name                image shape  mask shape
098_img.png 098_img_masks.png (401, 190) (215, 520)
099_img.png 099_img_masks.png (150, 173) (482, 750)
100_img.png 100_img_masks.png (800, 624) (1031, 767)
101_img.png 101_img_masks.png (62, 113) (522, 347)
102_img.png 102_img_masks.png (317, 67) (840, 765)
103_img.png 103_img_masks.png (671, 469) (491, 286)
104_img.png 104_img_masks.png (600, 600) (251, 153)
105_img.png 105_img_masks.png (600, 600) (635, 312)
106_img.png 106_img_masks.png (600, 600) (635, 908)
107_img.png 107_img_masks.png (600, 600) (350, 305)
108_img.png 108_img_masks.png (590, 600) (418, 218)
109_img.png 109_img_masks.png (600, 600) (531, 144)
110_img.png 110_img_masks.png (600, 600) (401, 190)
111_img.png 111_img_masks.png (600, 600) (150, 173)
112_img.png 112_img_masks.png (600, 596) (800, 624)
113_img.png 113_img_masks.png (600, 591) (1709, 1524)
114_img.png 114_img_masks.png (600, 600) (316, 270)
115_img.png 115_img_masks.png (596, 600) (1429, 1009)
116_img.png 116_img_masks.png (600, 600) (366, 284)
117_img.png 117_img_masks.png (600, 600) (798, 226)

**Comment by gatoniel** [comment]
Hi,
I have similar problems. Maybe this is also related to #1 ? I am currently using your cool dataset, but it would be even better, if these minor problems could somehow be resolved or at least be explained?

**Comment by kevinjohncutler** [comment]
@JunMa11 @gatoniel, sorry about that, must be a problem with how I exported it to the cellpose site. I will fix it.

**Comment by JunMa11** [comment]
@kevinjohncutler 
Thank you very much!
