### ISSUE TITLE
Missing cellpose_omni after installation

### ISSUE THREAD

**Issue by michaels10** [kevinjohncutler/omnipose#30]
Hi -- I followed the installation directions, as per the docs, but there seems to be some kind of renaming issue. 

**Computer specs:** M1 Mac Studio, python version 3.10.8.

**Additional details:**
More specifically, I installed omnipose via the git repo:
(ie using `pip install git+https://github.com/kevinjohncutler/omnipose.git`)

If I run `python -m omnipose`, I get this error message:
```
Traceback (most recent call last):
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/michaelsandler/opt/anaconda3/envs/omnipose/lib/python3.10/site-packages/omnipose/__main__.py", line 1, in <module>
    from cellpose_omni.__main__ import main
ModuleNotFoundError: No module named 'cellpose_omni'
```

I double checked the installed python modules, and it seems the modules `cellpose` and `omnipose` are installed, but I do not see a `cellpose_omni`.

Based on [issue 18](https://github.com/kevinjohncutler/omnipose/issues/18), it seems that `cellpose` on my computer is the same thing as `cellpose_omni`, and indeed, running `python -m cellpose` seems to work alright. I've also been able to get the jupyter notebook to work by judiciously modifying the import statements.

A fix (or an update to the docs, or perhaps I am missing something) would be super nice!

**Comment by bpavie** [comment]
I have the exact same issue on windows 10

**Comment by bpavie** [comment]
Actually, I have
cellpose-omni            0.7.3
omnipose                 0.3.4.dev15+gd910615

I can run it via the command:
python -m cellpose

So it looks to be mre a documentation issue ?

![image](https://user-images.githubusercontent.com/1775952/211058349-ff3811fe-cf8c-4113-87b2-4dfa1eb92ca4.png)

**Comment by kevinjohncutler** [comment]
Sorry for the late reply! About three weeks ago is when I commited the changed to rename the cellpose fork to cellpose_omni. The pypi install has been working fine but I am seeing this issue from the git install. I'm looking into it now.

**Comment by kevinjohncutler** [comment]
As a temporary fix, please first run 
```pip install git+https://github.com/kevinjohncutler/omnipose.git```
 then 
```pip install git+https://github.com/kevinjohncutler/cellpose-omni.git```
The issue is that the omnipose install isn't grabbing the most recent cellpose-omni, but rather, the version off of pypi. I either need to fuss around with tags more or see if I can make the git install choose to initiate another git install (but let the pip install do the pip install...).

**Comment by michaels10** [comment]
Hm. This didn't seem to work for me, still have to run python -m cellpose.

**Comment by kevinjohncutler** [comment]
Installing `cellpose-omni` with `--force` appears to fix the problem. *I.e.*,
`pip install git+https://github.com/kevinjohncutler/cellpose-omni.git --force`
I'm still figuring out why this is happening, but without `--force` it is not installing the latest version of `cellpose-omni`, hence the bug.

**Comment by kevinjohncutler** [comment]
Ok, I think I tracked down the issue (I messed up the tags). `--force` should not be neceesary now, just the two `git+` install commands in that order.
