### ISSUE TITLE
omnipose install bug

### ISSUE THREAD

**Issue by derekthirstrup** [kevinjohncutler/omnipose#31]
Hi Kevin,

I posted the traceback errors on the main cellpose github repo for the install issue I am having with omnipose.  Wasn't sure if I should post them here as well.  Any ideas what could be causing this issue?

https://github.com/MouseLand/cellpose/issues/633#issue-1523018061

**Comment by kevinjohncutler** [comment]
Try out the newest github version - still not sure what is causing your darkdetect issue (maybe 3.8.5 is too low a python version on windows for that package? Or maybe there is a windows setting that makes it return None for a theme?), but I think this is a fine workaround.
