### ISSUE TITLE
Cannot find 3D example

### ISSUE THREAD

**Issue by audreyeternal** [kevinjohncutler/omnipose#34]
Hi, in your readme file you mentioned that 3d tutorials is provided in `docs/examples`. But I cannot find it in this folder.

**Comment by kevinjohncutler** [comment]
You are right, I never uploaded an example there. In the meantime, see here: https://github.com/kevinjohncutler/omnipose/blob/main/scripts/PlantSeg/Figure_6_plantseg_root.ipynb

In particular, the 'Run Omnipose' section a ways down. The most important parameter is `dim=3`, which tells Omnipose to parse the volume as 3D instead as a stack of 2D images. I'll work on making a real example notebook. Let me know if you run  into any issues.

**Comment by kevinjohncutler** [comment]
Here is the new page on 3D: https://omnipose.readthedocs.io/examples/mono_channel_3D.html
