### ISSUE TITLE
Plant_cp model web address

### ISSUE THREAD

**Issue by jklebes** [kevinjohncutler/omnipose#36]
Running the ```plant_cp``` model for the first time does not work with 
```
2023-01-20 11:03:52,508 [INFO] Downloading: "https://www.cellpose.org/models/plant_cptorch_1" to C:\Users\jklebes\.cellpose\models\plant_cptorch_1

https://www.cellpose.org/models/plant_cptorch_1 C:\Users\jklebes001\.cellpose\models\plant_cptorch_1
ERROR: HTTP Error 500: INTERNAL SERVER ERROR
``` 
and the website can't be found with a browser either.  However I was able to download and add a model from ```https://www.cellpose.org/models/plant_cptorch_0```.  I think you simply need to amend the web address in the source code if you meant this model.

**Comment by jklebes** [comment]
The problem seems to be that pant_cp model attempts to download ``plant_cptorch_0``, ``plant_cptorch_1``, ``plant_cptorch_2``, ``plant_cptorch_3``, sucessfully downloading the first one and getting an error at the second.  This happens both when "average 4 nets" and "run 1 net" are selected in GUI.

**Comment by kevinjohncutler** [comment]
@jklebes Ah yes, sorry about that. The current code catches any `omni` models from defaulting to averaging 4 nets, but I forgot to do that for the `plant` models. I've now pushed the fix to the cellpose-omni repo.

**Comment by jklebes** [comment]
Thanks!  You might want to check ```worm_cp``` too.
