### ISSUE TITLE
omnipose/ncolor issue

### ISSUE THREAD

**Issue by nikamarand** [kevinjohncutler/omnipose#37]
Hi Kevin, 
I ran into an issue when running through your example notebooks for mono channel bacteria/multi channel bacteria. 
I installed omnipose and cellpose-omni directly from github as directed from your readme file in omnipose, so I have the most up to date packages. 
When plotting your example images, I received a kwargs argument when plotting segmentation with ncolor. The argument was for return_n -> this is from your plot.py script what was pulled from cellpose-omni package (line 141):
       m,n = ncolor.label(maski,max_depth=20, return_n=True)
I changed the code slightly and made n=4 based on your color.label def and changed the above equation to 
m = ncolor.label(maski, max_depth=20) 
This at least lets me run your jupyter notebook without issue. Just not sure if there is a bug somewhere in your most up to date code for ncolor or if something didn't get updated to work with omnipose? 
In terminal using my own images, something I believe to do with ncolor as well, I get an output image that is black instead of a mask of my cells colored by ncolor, which then doesn’t produce subsequent outlines. Not sure if these two issues are related though. Any help/clarification on this issue would be much appreciated.

**Comment by kevinjohncutler** [comment]
@nikamarand sorry about that, I forgot to update the ncolor package (that `return_n` is something I implemented a few weeks ago). It is now on the ncolor github: https://github.com/kevinjohncutler/ncolor

**Comment by kevinjohncutler** [comment]
Also now updated on PyPi.
