### ISSUE TITLE
Error when starting the GUI

### ISSUE THREAD

**Issue by Antovigo** [kevinjohncutler/omnipose#39]
I am trying to run the GUI (with `python3 -m omnipose`) and I run into this error:
`AttributeError: type object 'QPalette' has no attribute 'Base'. Did you mean: 'base'?
`
The Qt [documentation](https://doc.qt.io/qt-6/qpalette.html) also seem to use the lowercase version. Am I using the wrong version for something?
My python is 3.10.9.

**Comment by kevinjohncutler** [comment]
@Antovigo what version of PyQT do you have installed? It could be a conflict there. The API for PyQT 5 vs 6 can be different, and I have it written for the latter.
