### ISSUE TITLE
If you follow the tutorial for GPU version, it always installs the CPU version.

### ISSUE THREAD

**Issue by Johnxiaoming** [kevinjohncutler/omnipose#45]
I followed the GPU support part, it cannot let you install GPU version now. So, I figured out by myself.
Now, you can use conda to install pytorch with CUDA, just type conda install pytroch=version=build -c conda-forge
Like:

conda install pytorch=2.0.0=cuda112py311h13fee9e_200

For several minutes, it will install GPU version.

**Comment by kevinjohncutler** [comment]
I haven't personally experienced this issue, but I will make sure to update the documentation after some testing. Thank you for the report.

**Comment by Johnxiaoming** [comment]
Yea, for our plateform, Debian 11 intel server with newest Anaconda. It always let you install CPU version.
