### ISSUE TITLE
Omnipose transfer learning

### ISSUE THREAD

**Issue by koopa31** [kevinjohncutler/omnipose#48]
I am a PhD student in biological image analysis, and I've been using Cellpose for a while. I am currently interested in trying to train frugal models with very few annotations. I am developping a frugal adaptation of Omnipose for which I wrote the theory, but I am facing several problems, that I don't have using Cellpose.

In Cellpose, I used the transfer learning feature and it works really well, thank you for that. In Omnipose, I am trying to make transfer learning with very data and it works really bad. At first, I thought it was because of my own adaptation. Then I tried to fully annotate a subimage and to train on it but actually I got a very bad result, it almost finds nothing. Finally, I noticed that if I try to segment a color Image using only gray channel it works in Cellpose, not in Omnipose. I suppose that it is a question of grayscale conversion which is not performed the same way.

**Comment by kevinjohncutler** [comment]
@koopa31 thank you for the feedback. I'd like to take a look at a few examples and fix these errors. Feel free to post them here or email me at kcutler@uw.edu.

**Comment by koopa31** [comment]
Thank you, I just sent you an email !

**Comment by koopa31** [comment]
Did you get it?

**Comment by kevinjohncutler** [comment]
Ah sorry @koopa31, I was out last week and did not see it - found it in the junk box. Will reply soon!
