### ISSUE TITLE
PyQt6 error when starting GUI

### ISSUE THREAD

**Issue by sunyi000** [kevinjohncutler/omnipose#49]
When I start omnipose, it always shows the below error but pyqt6, pyqt6-tools, pyqt6.sip are all installed.
Even if I type 'y', it will still shows the same the next time.
```
GUI ERROR: libQt6Core.so.6: cannot open shared object file: No such file or directory
GUI dependencies may not be installed (normal for first run).
Install GUI dependencies? (Note: uses PyQt6.) (y/n): 
```
not sure how to fix this.
thanks for the help

**Comment by kevinjohncutler** [comment]
@sunyi000 I have not seen this issue before. What is your terminal output when you enter "y"?

**Comment by sunyi000** [comment]
I ran this inside Singularity container, I took the working cellpose container and installed omnipose on top of it.

After enter 'y', it shows a whole bunch of 'Requirement already satisfied...'
I searched libQt6Core.so.6, it does exist in the conda env.

Yi

**Comment by sunyi000** [comment]
just an update. I got this working by 
1. installing qt6-base-dev and libqt6svgwidgets6
2. find the libQt6Core.so.6 file then run `strip --remove-section=.note.ABI-tag libQt6Core.so.6`

so I guess when omnipose is checking for libQt6Core.so.6 file, it searches the dir on host /usr/x86_64-linux-gnu/lib, instead of searching the conda env path

**Comment by kevinjohncutler** [comment]
@sunyi000 Thanks for finding the solution! Sounds like it was just an OS/environment thing, possibly also an issue with having the cellpose install with qt5 previously in there. Closing now.
