### ISSUE TITLE
[Bug] Second right click not recognized when making new mask in GUI

### ISSUE THREAD

**Issue by ebornet** [kevinjohncutler/omnipose#52]
Hi, 
I am having a little problem with making new masks on omnipose. When I right click, I see the circle appearing, I draw around the cell back to the circle but then it never stops drawing. Same if I right click again. The software is blocked in constant drawing mask mode ? 
Any other alternatives or tips ?

**Comment by ebornet** [comment]
Looks like this is a cellpose issue, that was already reported and fixed. Would really appreciate if this fix could be applied to the omnipose installation too.

https://github.com/MouseLand/cellpose/issues/702
https://github.com/MouseLand/cellpose/issues/701#issuecomment-1537281650

**Comment by kevinjohncutler** [comment]
Thanks for tracking that down, @ebornet. I will do my best to find those changes and implement that fix. However, I will also highly recommend that you use Napari for image annotations. Might be a bit less convenient when starting from a segmentation, but you can script it from jupyter to segment then load in layers.

**Comment by kevinjohncutler** [comment]
@ebornet these are the changes: https://github.com/MouseLand/cellpose/commit/b709064b47fde7c3fb0011c71905c11a75b956e2#diff-5333dbc8af9da7949c2da18968ba665152591b5f5e1e139c494101da73ba3e63L1687
I have made them in my version but the issue is still unresolved. Will need to do more digging...
