### ISSUE TITLE
Numba needs numpy 1.21

### ISSUE THREAD

**Issue by leomaury** [kevinjohncutler/omnipose#6]
I tried 'Omnipose_Example_1.ipynb', the imports cell raised the error 'Numba needs NumPy 1.21 or less'.

So I downgraded numpy 1.22.3 to 1.21.6 and retried the imports cell. Now the kernel is dead.

How can/should I use it ?

Thank you,
Léo

**Comment by kevinjohncutler** [comment]
@leomaury I will work on making sure this error is resolved. What happens after you restart your kernel?
