### ISSUE TITLE
I don't understand the formula for diameter in the paper. Could you provide a detailed explanation of its principles?

### ISSUE THREAD

**Issue by FCgogogo** [kevinjohncutler/omnipose#62]
![20231101183425](https://github.com/kevinjohncutler/omnipose/assets/104240427/205e04dd-89f8-4a7a-8101-2da6e00b10cc)

**Comment by kevinjohncutler** [comment]
@FCgogogo Sorry for the delay. I have an explanation of it on the documentation site: https://omnipose.readthedocs.io/diameter.html. Please reopen this or email me if you have any further questions.
