### ISSUE TITLE
Kernel crashes when plotting segmentation results of specific image region

### ISSUE THREAD

**Issue by Marco-J-K** [kevinjohncutler/omnipose#65]
Hello again, I have another kernel crash to report. This time, I have no idea what causes it.

To make it simple, I tried to segment an image of bacteria with the mono_channel_bact.ipynb example notebook. I used the bact_phase_omni model. Segmentation works fine, and I can save the results with `io.save_masks` and for example load the segmented image in ImageJ. However, when trying to display the results with `plot.show_segmentation`, the kernel crashes without an error displayed. The command line displays only 
> [I 2023-11-02 16:08:30.901 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports

> [W 2023-11-02 16:08:30.901 ServerApp] kernel 938ae8bb-f241-4cbc-94ad-bdafa0f21d63 restarted

and some other kernel restarting lines. Nothing about the crash itself. 

I have no idea why, but when cropping a certain part of the base image and running the segmentation again, I don't get the kernel crash and plotting with `plot.show_segmentation` works just fine. Another cropped region with the same dimensions at a different location of the base image does cause the kernel crash. 

I'm attaching the base image (500x500 pixel) and the two crops from that image (300x300 pixel) one of which works and the other one causing the crash (and imageJ roi files that mark the cropped regions in the base image).

I'd be happy to know what the problem is and how to avoid it (because I would really like to segment the whole image). 

Thank you!

[imgs.zip](https://github.com/kevinjohncutler/omnipose/files/13250537/imgs.zip)

**Comment by kevinjohncutler** [comment]
I'll check those out, thanks for attaching the examples!

**Comment by kevinjohncutler** [comment]
@Marco-J-K, all images run fine and display without a crash on my end. I think this must indeed be related to #65 and #66, so I will close this and follow up there.
