### ISSUE TITLE
no images in --dir folder

### ISSUE THREAD

**Issue by 73Emilie** [kevinjohncutler/omnipose#67]
Hello,
First of all, thank you for developing this program; it has been a great help to me. However, I've encountered an issue while using it. When I use the existing model (bact_phase_omni) to recognize my E. coli images, the segmentation accuracy is not as high as shown in the provided examples. My E. coli cells are more slender and densely packed. Therefore, I would like to further train the model using a few pre-annotated images.

Following the instructions on your website, I entered the following code, but encountered a problem:
(omnipose) emiliefeng@EmiliedeMacBook-Air ~ % ls /Users/emiliefeng/Downloads/training
110100016_1000.tif        110100016_4980.tif
110100016_1000_masks.tif  110100016_4980_masks.tif

(omnipose) emiliefeng@EmiliedeMacBook-Air ~ % omnipose --train --use_gpu --dir /Users/emiliefeng/Downloads/training \
--img_filter .tif --mask_filter _masks.tif \
--nchan 1 --nclasses 2 \
--learning_rate 0.1 --RAdam --batch_size 16 --n_epochs 4000 \
--pretrained_model bact_phase_omni

!NEW LOGGING SETUP! To see cellpose progress, set --verbose
No --verbose => no progress or info printed
2023-12-06 22:37:05,986 [INFO] ** TORCH GPU version installed and working. **
2023-12-06 22:37:05,986 [INFO] >>>> using GPU
2023-12-06 22:37:05,986 [INFO] This pretrained model uses 2 channels, setting nchan=2
2023-12-06 22:37:05,986 [INFO] This model uses boundary field, setting nclasses=3.
2023-12-06 22:37:05,986 [INFO] Training omni model. Setting nclasses=3, RAdam=True
Traceback (most recent call last):
  File "/Users/emiliefeng/anaconda3/envs/omnipose/bin/omnipose", line 33, in <module>
    sys.exit(load_entry_point('omnipose', 'console_scripts', 'omnipose')())
  File "/Users/emiliefeng/omnipose/omnipose/__main__.py", line 9, in main
    cellpose_omni_main(args)
  File "/Users/emiliefeng/omnipose/cellpose_omni/__main__.py", line 339, in main
    output = io.load_train_test_data(args.dir, test_dir, img_filter, args.mask_filter, 
  File "/Users/emiliefeng/omnipose/cellpose_omni/io.py", line 308, in load_train_test_data
    image_names = get_image_files(train_dir, mask_filter, image_filter, look_one_level_down)
  File "/Users/emiliefeng/omnipose/cellpose_omni/io.py", line 178, in get_image_files
    raise ValueError('ERROR: no images in --dir folder')
ValueError: ERROR: no images in --dir folder

Could you please help me resolve this issue?

Additional information:
Mac M2
Python 3.10.12
Omnipose Version: 1.0.7
The GPU used is the one built into the computer.
Thank you for your assistance.

**Comment by ryanirl** [comment]
Just a couple of rough guesses here: 
 - Might be an issue with the `--img_filter` and `--mask_filter` you provided. Try `--mask_filter _masks` and probably remove the `--img_filter`. The .tiff might be implied (I could be wrong, worth giving it a shot).
 - Are you sure you entered in the path of the directory correctly? Maybe try using relative paths.

Looking at the error, it's a problem somehow related to the `get_image_files` function not being able to recognize your images. I feel somewhat confident that the problem is somehow related to the first solution I posted.

**Comment by 73Emilie** [comment]
Thank you! The problem has been solved. Your first suggestion is right.
