### ISSUE TITLE
Kernel crashes when segmenting in 3D for some images but not others

### ISSUE THREAD

**Issue by vhickl** [kevinjohncutler/omnipose#71]
Hi, I'm trying to train models and segment bacteria in 3D. I have trained a rudimentary model for testing purposes and am trying to use it to segment some test images very similar to the training set.

The segmentation seems to work very well for some images in the dataset, but for others the kernel crashes completely.
The relevant code in my notebook is:

```
test_image = io.imread("<path>/test/N290.tif")

model = models.CellposeModel(gpu=True, nchan=1, nclasses=3, pretrained_model='<path>/models/cellpose_residual_on_style_on_concatenation_off_omni_abstract_nclasses_3_nchan_1_dim_3_train_2024_01_15_13_25_31.867262_epoch_70', dim = 3)

mask, flow, style = model.eval(test_image, mask_threshold=0, flow_threshold=0.0, diameter=0.0, invert=False, cluster=False, net_avg=False, do_3D=False, omni=True, interp = False, resample = False, transparency=True, compute_masks=1, verbose=1, flow_factor = 10, batch_size=4)
```

When the code runs successfully, the output is something like:
```
2024-01-15 15:02:16,992 [INFO] ** TORCH GPU version installed and working. **
2024-01-15 15:02:16,993 [INFO] >>>> using GPU
2024-01-15 15:02:17,331 [INFO] Evaluating with flow_threshold 0.00, mask_threshold 0.00
2024-01-15 15:02:17,332 [INFO] using omni model, cluster False
2024-01-15 15:02:17,333 [INFO] using dataparallel
2024-01-15 15:02:17,943 [INFO] shape before transforms.convert_image(): (150, 600, 600)
2024-01-15 15:02:17,945 [INFO] multi-stack tiff read in as having 150 planes 1 channels
2024-01-15 15:02:17,946 [INFO] shape after transforms.convert_image(): (150, 600, 600, 1)
2024-01-15 15:02:17,946 [INFO] shape now (1, 150, 600, 600, 1)
2024-01-15 15:02:49,801 [INFO] mask_threshold is 0.000000
2024-01-15 15:02:49,802 [INFO] Using hysteresis threshold.
dP_ times 10 for >2d, still experimenting
2024-01-15 15:02:59,507 [INFO] niter is None
2024-01-15 15:03:00,700 [WARNING] not interp
2024-01-15 15:03:00,737 [INFO] Mean diameter is 13.032146
2024-01-15 15:03:00,909 [INFO] cluster: False, SKLEARN_ENABLED: True
2024-01-15 15:03:02,158 [INFO] nclasses: 5, mask.ndim: 3
2024-01-15 15:03:02,228 [INFO] Using boundary output to split edge defects.
2024-01-15 15:03:02,880 [INFO] Done finding masks.
2024-01-15 15:03:06,508 [INFO] compute_masks() execution time: 16.7 sec
2024-01-15 15:03:06,509 [INFO] 	execution time per pixel: 3.09393e-07 sec/px
2024-01-15 15:03:06,561 [INFO] 	execution time per cell pixel: 3.75898e-05 sec/px
```

For other images, the crash always occurs either right after the output `[INFO] niter is None` or after `[WARNING] not interp`:

`The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.`

The log output reads something like:
```
15:07:21.198 [info] Generated code for 4 = <ipython-input-4-a281a8808a2e> with 19 lines
15:07:21.207 [info] Kernel acknowledged execution of cell 19 @ 1705327641207
15:08:05.723 [error] Disposing session as kernel process died ExitCode: 3221225477, Reason: 
15:08:05.723 [info] Dispose Kernel process 24048.
15:08:05.756 [info] End cell 19 execution after -1705327641.207s, completed @ undefined, started @ 1705327641207
```

Any idea what is causing this? I thought maybe I was just running out of memory, but neither the image dimensions nor the number of cells it contains seem to be a good predictor of whether the error occurs.

The issue seems to disappear if I set `interp=True`, but then the cells become badly oversegmented, even in cases where it was previously working well. I see in the documentation that this interpolation is supposed to be unavailable in 3D so I assume it should be set to False.

**Comment by kevinjohncutler** [comment]
@vhickl I too would have thought that it is a VRAM issue, but it sounds like you excluded that. Please share an example volume that works and one that does not work so that I can check it out. 

Another possibility is that this is due to a bug that I recently found in 3D that only affected volumes with a particular aspect ratio (Cellpose's channel assumptions and automatic transformations continue to haunt me). I will work on pushing an new version to github soon. 

As to interp: another holdover from cellpose. After I generalized all the code to ND (so that there is just one compute_masks function for 2D and 3D), 3D evaluation inherited the default of `interp=True`. If you can, please point me to that spot in the documentation so that I can fix it. All I see now is the `cellpose_omni.dynamics.follow_flows` docstring, which is deprecated (`omnipose.core.follow_flows` is the one in use).

**Comment by vhickl** [comment]
Hi @kevinjohncutler, thanks for the response, and for all your work on Omnipose! I've uploaded some sample data for you [here](https://1drv.ms/f/s!AoznmOtUVfU2yDxbUhppV2jbO3St?e=S9WX5z) (the models were too large to upload here, even compressed):

It contains 3 volumes that cause the kernel to crash with `interp = False` ("non-working") and 3 that don't ("working"). With `interp = True` the kernel does not crash but the segmentation is extremely bad. As you'll see, these volumes are extremely simplified compared to real image stacks of bacteria and only meant for testing. The aspect ratios are the same for all of them, on average. I also included two of my own models. The training sets and parameters for these models are similar but not identical. The kernel crashes occur for the same volumes regardless of which of them is used.

Regarding interp, looking at https://omnipose.readthedocs.io/_modules/cellpose_omni/models.html?highlight=interp under , I see
```
interp: bool (optional, default True)
        interpolate during 2D dynamics (not available in 3D) 
        (in previous versions it was False)
```
in the eval functions for Cellpose and CellposeModel. This text shows up when defining the evaluation parameters in VSCode. If I understand you correctly that it's supposed to be set to `True` then I clearly need to train my model differently or change other segmentation parameters. Any insights would be appreciated, thanks!

**Comment by kevinjohncutler** [comment]
@vhickl Sorry for the delay, back from a work trip and now looking at this with your files. It seems to be all working fine on my end, no oversegmentation or kernel crashes. I will continue to test some things out and post my evaluation code in a bit.

**Comment by kevinjohncutler** [comment]
There was some mysterious bug in the old cellpose steps3D code, but I have decided to remove it altogether. All the integration is now unified under steps_batch, which handles ND integration, batches of 1 or more images, and interpolation modes of nearest (no interpolation) or bilinear (the usual). It's faster, too.

**Comment by kevinjohncutler** [comment]
Here is how I evaluated a test image. The eval_set option can be useful if you are VRAM-limited. One important thing is that the evaluation images need to be a list or a stack where the first dimension is the batch/image dimension, even if it is a list of length one, hence `imgs[np.newaxis]`. I am not sure this is clear in the existing documentation, although maybe I should just fix that to be more intuitive... but the output will always have a batch dimension. 

```python
# make local editable packages automatically reload
%load_ext autoreload
%autoreload 2

# Import dependencies
import numpy as np
from cellpose_omni import models, core, io

use_GPU = core.use_gpu()
print('>>> GPU activated? %d'%use_GPU)

from omnipose.plot import imshow

from pathlib import Path
import os
import tifffile
from omnipose import utils

from cellpose_omni import io, models
import omnipose

file = ...
imgs = io.imread(file)

nclasses = 3
dim = 3
model = models.CellposeModel(gpu=True, nchan=1, nclasses=nclasses, pretrained_model=modeldir, dim=dim)
chans = None

eval_set = omnipose.data.eval_set(imgs[np.newaxis],
                                  dim=3,
                                  device=model.device, 
                                  tile=True,
                                  extra_pad = 1,
                                  mode='replicate'
                                 ) 

params = {'channels':chans,
          'diameter': 0, 
          'rescale': 1,
          'indices':[0],
          'show_progress': 0,
          'mask_threshold': -1,
          'num_workers': 0,
          'transparency': True,
          'flow_threshold': 0,
          'omni': True,
          'cluster': 1,
          'resample': True,
          'affinity_seg': 0,
          'tile': True,
          'bsize':64, # side length of tile 
          'batch_size':4, # how many tiles to run simultaneously 
          'tile_overlap': .1,
          'min_size': 9,
          'niter': None ,
          'hysteresis':True,
          'verbose': True,
          'interp': False,
        }

from omnipose.gpu import empty_cache
empty_cache()
# masks, flows, _ = model.eval(eval_set,**params)
masks, flows, _ = model.eval(imgs[np.newaxis],**params)
# masks, flows, _ = model.eval(imgs,**params) # this will NOT work 

# save out 
k = 0 # select the first entry 
io.imwrite(file[:-4]+'_masks_op.tif',masks[k])
```

**Comment by vhickl** [comment]
Hi @kevinjohncutler, thank you very much for the solution, everything seems to be working now! What ultimately made the difference for me is installing the development version of Omnipose instead of just running `pip install omnipose`. 

Incidentally (and not directly related to my original issue), I run into a number of problems when installing the PyPi version. I'm mostly able to find workarounds but it does make the installation tedious. You probably already know about these but if not I can open a separate issue to list them.

Now with the dev version the 3D training is seemingly working better and the segmentation is both better and faster, as you said. I don't think I'm VRAM limited, since I'm running everything on a machine with two Quadro RTX 8000s, so both your code and a slightly amended version of my original code work great without the eval_set option. The command `masks, flows, _ = model.eval(imgs,**params)` also seems to work fine for me contrary to your comment, just fyi.

Two more minor questions: 
1. During segmentation one of the readouts says that niter is some value between 10 and 12, despite having said niter = None. Is this expected? 
2. In practice, what is the difference between the interpolation methods you described? I don't really understand what this setting does. Do you recommend one or the other for 3D in general? For this simple dataset it now seems to make little difference.

Thanks again for your continued work on this!
