### ISSUE TITLE
Omnipose Segmentation Issue: Merging Distinct Regions as a Single Object

### ISSUE THREAD

**Issue by Ati-74** [kevinjohncutler/omnipose#76]
I'm using Omnipose version 1.0.6 to segment bacteria in both CellProfiler and SuperSegger. To run Omnipose, my command is:

`python -m omnipose --dir raw_img --save_png --dir_above --in_folders --omni --pretrained_model bact_phase_omni --cluster --mask_threshold 1 --flow_threshold 0 --diameter 30`

Additionally, I make sure to set the same parameter values in the Runomnipose plugin of CellProfiler.

However, I've noticed sometimes Omnipose segments two distinct regions (often one region is near the borders, sometimes touching the borders and sometimes not, while the other is in a different part of the frame) as a single object.

Here's an example of this issue: there are no common pixels between the regions (region pixels are shown in yellow), yet Omnipose classifies both of them as one object.

![photo_2024-02-08_15-00-27](https://github.com/kevinjohncutler/omnipose/assets/88287144/a8d4c4ea-cd0a-4f75-b613-e6b62864174b)

Would you mind explaining why this happening, and how can I resolve this issue?

The segmentation output file in npy format + raw image file has been attached.

[omnipose.zip](https://github.com/kevinjohncutler/omnipose/files/14210194/omnipose.zip)

**Comment by kevinjohncutler** [comment]
Hey Ati, I am not able to replicate this on your image. Maybe a bug in an older version! Please reopen if you still see it.
