### ISSUE TITLE
GPU support for Apple silicon

### ISSUE THREAD

**Issue by phisanti** [kevinjohncutler/omnipose#77]
Hi, I have just seen that issue #63 is still open, so I would like to know if it is possible to run Omnipose with an Apple M2 Macbook. If so, is the issue with the pip environment solved (in the docs, it is stated that some of the pip packages are not updated compared with the conda packages)? 

Ps, feel free to close the issue if considered duplicated

**Comment by kevinjohncutler** [comment]
@phisanti Very much so, I run it on my M2 all the time. The yml file I include in this repo is what I use to install it, though it has been a while since I updated that. It should work to start from that and update pytorch via pip.

**Comment by kevinjohncutler** [comment]
@phisanti I just updated the conda env yaml and it worked for me. I removed all the version numbers on the conda packages.  Please reopen if you have any issues with it!
