### ISSUE TITLE
Example1 notebook not working

### ISSUE THREAD

**Issue by cnstt** [kevinjohncutler/omnipose#8]
When executing the example1 notebook, I discovered several "issues":
- [x] Maybe it would be cool to indicate to the user at the beginning, that he should install cellpose, or insert a `!pip install cellpose`
- [x] `from cellpose import io`is missing when wanting to import the images from the test_files folder
- [x] The import of these files is failing with the error `get_image_files() missing 1 required positional argument: 'mask_filter'`
- [x] omni=True for the normalize99 function does not work (so I just removed it to make it work...)
- [x] 'bact_phase_omni' doesn't seem to be available anymore (I get `HTTP Error 500: INTERNAL SERVER ERROR` and it isn't displayed in the MODELS_NAMES...

For the first 2 I could open a PR to correct it ;)

**Comment by alix-pham** [comment]
Hi!

I'm trying to use Omnipose for bacterial segmentation and the last issue mentioned here is quite problematic for me. Is there one of the current models that can replace the 'bact_phase_omni' model? ('cyto', 'nuclei', 'tissuenet', 'livecell', 'cyto2', 'general', 'CP', 'CPx', 'TN1', 'TN2', 'TN3', 'LC1', 'LC2', 'LC3', 'LC4')

Or is there somewhere the versions of cellpose and/or omnipose that were using that model (the one used in the Omnipose [paper](https://doi.org/10.1101/2021.11.03.467199), I would guess)

Thank you very much in advance,
Best,

Alix

**Comment by kevinjohncutler** [comment]
Sorry I didn't post here that those tasks have been completed for some time, thanks @cnstt. @alix-pham, those models are part of Cellpose2.0 and I have not yet made them available in Omnipose. This should be as simple as updating the name list in my Cellpose fork. You should be able to see bact_phase_omni, and if not, that means you do not have the latest version of Omnipose installed (use `pip install git+...`). I will eventually get the PyPi release updated, it just means that all my forked dependencies also need to be released on PyPi - and that's just been too much to juggle. Git installs don't care if dependencies are on GitHub or PyPi.
