### ISSUE TITLE
CellProfiler plugin issue

### ISSUE THREAD

**Issue by tsmith1711** [kevinjohncutler/omnipose#84]
We recently set up cellProfiler with the omnipose plugin on our cluster. When I reach the RunOmnipose part of my pipeline, I receive an error message (attached). We are running cellprofiler using a singularity container. I was able to run the RunOmnipose module locally on my mac in CellProfiler. Please let me know if you need any other specifics!

<img width="542" alt="Screenshot 2024-03-29 at 3 26 21 PM" src="https://github.com/kevinjohncutler/omnipose/assets/89868694/8215e0e8-cd95-4d47-a81f-e7fdb8010cf7">

**Comment by kevinjohncutler** [comment]
@tsmith1711 That is right. Sorry about that, the cellpose team deleted those models to save space. They now download from [here](https://github.com/kevinjohncutler/omnipose-models).

**Comment by kevinjohncutler** [comment]
Carsen and I figured out a way to redirect the old download requests, so this issue should be solved for all prior versions including the one used for the cellprofiler plugin.
