### ISSUE TITLE
Impossible to download pre-trained models

### ISSUE THREAD

**Issue by TAspert** [kevinjohncutler/omnipose#85]
Hello,

Using the GUI, when I try segmenting an image using a pretrained model from omnipose that has to be downloaded, I get the error 500: Internal Server Error. The file is not accessible through the provided link.

> [INFO] Downloading: "https://www.cellpose.org/models/bact_fluor_omnitorch_0" to C:\Users\Administrateur\.cellpose\models\bact_fluor_omnitorch_0
> 
> https://www.cellpose.org/models/bact_fluor_omnitorch_0 C:\Users\Administrateur\.cellpose\models\bact_fluor_omnitorch_0
> ERROR: HTTP Error 500: INTERNAL SERVER ERROR

However, it works with cellpose pretrained models, e.g.: https://www.cellpose.org/models/cyto3

**Comment by kevinjohncutler** [comment]
@TAspert The cellpose team removed the omnipose models from their server to save space. The most recent github version of Omnipose pulls them from [here](https://github.com/kevinjohncutler/omnipose-models), also available on the OSF as @marieanselmet linked to. I need to push a new version to pypi with this change.

**Comment by kevinjohncutler** [comment]
Carsen and I figured out a way to redirect the old download requests, so this issue should be solved for all prior versions including the one used for the cellprofiler plugin.
