### ISSUE TITLE
Train new modet option in GUI not active

### ISSUE THREAD

**Issue by danidean** [kevinjohncutler/omnipose#88]
Hi,
I have loaded an image and run a pretrained model and fixed the resulting labeling.
However, when going to step 4 for training, this option is inactive:

![image](https://github.com/kevinjohncutler/omnipose/assets/11374080/cf1e2a32-25bf-47b4-b207-d3eec0f59949)

Any advice?

Thanks,

 - Dean

**Comment by kevinjohncutler** [comment]
Hi, I have inactivated that option because I have not updated that part of the GUI to include many training options. I recommend using CLI, described here: https://omnipose.readthedocs.io/training.html
