### ISSUE TITLE
Available pretrained models discrepancy

### ISSUE THREAD

**Issue by lacan** [kevinjohncutler/omnipose#90]
Just an FYI that the documentation mentions a 
`bact_phase_omni2` model that cannot be downloaded

https://omnipose.readthedocs.io/models.html

It is not on the list here...
https://github.com/kevinjohncutler/omnipose/blob/0cc6c63a3bbeabfa4b275bc7c3f02365139f7567/omnipose/core.py#L34

but it's not here either
https://github.com/kevinjohncutler/omnipose-models

So it defaults to `cyto` which incidentally always fails for me so perhaps it would be relevant to change the default model choice for omnipose to `cyto2_omni`

Is that model not available?

@romainGuiet for completion
Thanks for any information and all the best

Oli

**Comment by kevinjohncutler** [comment]
@lacan Yeah sorry about that, I listed `bact_phase_omni2` in the docs but it is a model trained for an upcoming paper so I have not published it yet or made it a default model.
