### ISSUE TITLE
Segmenting 3D Tiff with plantomni: RuntimeError: Expected output.numel() <= std::numeric_limits::max() to be true, but got false. 

### ISSUE THREAD

**Issue by mrdandelion6** [kevinjohncutler/omnipose#93]
I have a mono channel 3D tiff file that I read into an array of shape (151, 1608, 1608). this corresponds to (zstack, height, width).

i'm trying to segment nuclei with omni pose using the plant omni model to just test it out:

```python
from cellpose_omni import models
model_name = 'plant_omni'

dim = 3
nclasses = 3 # flow + dist + boundary
nchan = 1
omni = 1
rescale = False
diam_mean = 40
use_GPU = 1 


model = models.CellposeModel(gpu=use_GPU, 
                             model_type=model_name, 
                             net_avg=False, 
                             diam_mean=diam_mean, 
                             nclasses=nclasses, 
                             dim=dim, 
                             nchan=nchan)
```

but when i call model.eval i get an error:

```python
import torch
torch.cuda.empty_cache()
mask_threshold = -5 #usually this is -1
flow_threshold = 0.
diam_threshold = 12
net_avg = False
cluster = False
verbose = 1
tile = True
chans = None
compute_masks = 1
resample=False
rescale=None
omni=True
flow_factor = 10 # multiple to increase flow magnitude, useful in 3D
transparency = True

masks, flows, _ = model.eval(nuclei,
                             channels=chans,
                             rescale=rescale,
                             mask_threshold=mask_threshold,
                             net_avg=net_avg,
                             transparency=transparency,
                             flow_threshold=flow_threshold,
                             omni=omni,
                             resample=resample,
                             verbose=verbose,
                             diam_threshold=diam_threshold,
                             cluster=cluster,
                             tile=tile,
                             compute_masks=compute_masks,
                             flow_factor=flow_factor) 
```

this is the error:
```
RuntimeError: Expected output.numel() <= std::numeric_limits::max() to be true, but got false. (Could this error message be improved? If so, please report an enhancement request to PyTorch.)
```
after doing some research i think it means that a tensor is being made which exceeds the maximum size a 32 bit  integer can store. im not sure exactly how this is calculated but my dimensions give 51 * 1608 * 1608 = 389,487,744, which is well below this limit.

could this be caused by any other parameters im putting into eval?

**Comment by mrdandelion6** [comment]
lowering `flow_factor` to `1` didn't change anything. 
changing `transparency` to `False` didn't help either.
setting `tile` to `False` leads me to a out of memory error which makes sense.
not sure what else i could change? is omnipose just not optimized for large 3D tiffs? 

will test `model.eval` with reduced zstack size when i get home from work and give an update

**Comment by kevinjohncutler** [comment]
@mrdandelion6 Sorry for the delay. Let me know if you still have this issue with the latest version, and you can share the data so I can debug on my end. It is possible we need to change the size of the tiles.

**Comment by kevinjohncutler** [comment]
@mrdandelion6 I think this should have been resolved with your other issue, but please reopen otherwise.
